name: Upload sources, binaries etc.

on:
  workflow_dispatch

env:
  LIB_VERSION: 1.1.61

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        clean: 'true'
        fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle clean
      run: ./gradlew clean --info
    - name: Build with Gradle
      run: ./gradlew -Pversion=${{ env.LIB_VERSION }} kotlinUpgradeYarnLock build --info
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.LIB_VERSION }}
        tag_name: ${{ env.LIB_VERSION }}
        body: ${{ github.event.head_commit.message }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-jvm-${{ env.LIB_VERSION }}.jar
        asset_name: GrowthBook-${{ env.LIB_VERSION }}.jar
        asset_content_type: application/x-jar
    - name: Upload sources
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-kotlin-${{ env.LIB_VERSION }}-sources.jar
        asset_name: GrowthBook-kotlin-${{ env.LIB_VERSION }}-sources.jar
        asset_content_type: application/x-jar
    - name: Upload metadata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-metadata-${{ env.LIB_VERSION }}.jar
        asset_name: GrowthBook-metadata-${{ env.LIB_VERSION }}-all.jar
        asset_content_type: application/x-jar
